version: 2.1

executors:
  linux_arm64:
    machine:
      image: ubuntu-2004:2023.07.1
    resource_class: arm.medium

jobs:
  publish-docker-image-arm64:
    executor: linux_arm64
    steps:
      - checkout
      - run:
          name: check if emscripten-releases-tags.json has changed
          command: |
            CHANGED_FILES=$(git diff --name-only <<pipeline.git.base_revision>>..<<pipeline.git.revision>>)
            if [[ ! $CHANGED_FILES =~ "emscripten-releases-tags.json" ]]; then
              echo "emscripten-releases-tags.json has not changed, skipping build and publish"
              circleci-agent step halt
            fi
      - run:
          name: extract latest emscripten arm64 linux version
          command: |
            export ARM64_VERSION=$(grep -oP '(?<="latest-arm64-linux": ")[^"]*' emscripten-releases-tags.json)
            export ARM64_IMAGE_TAG=${ARM64_VERSION}-arm64
            echo "ARM64_VERSION=$ARM64_VERSION"
            echo "ARM64_IMAGE_TAG=$ARM64_IMAGE_TAG"
            if [ -z "$ARM64_VERSION" ]; then
              echo "ARM64_VERSION is empty, skipping publish"
              circleci-agent step halt
            fi
      - run:
          name: check if docker image already exists
          command: |
            DOCKER_IMAGE_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/emscripten/emsdk/tags/$ARM64_IMAGE_TAG)
            if [ "$DOCKER_IMAGE_EXISTS" = "200" ]; then
              echo "Docker image already exists, skipping build and publish"
              circleci-agent step halt
            fi
      - run:
          name: build
          command: make -C ./docker version=${ARM64_VERSION} build
      - run:
          name: test
          command: make -C ./docker version=${ARM64_VERSION} test
      - run:
          name: push image
          command: |
            echo "./docker version=${ARM64_VERSION} alias=${ARM64_IMAGE_TAG} only_alias=true push"

workflows:
  build-docker-image:
    jobs:
      - publish-docker-image-arm64:
          filters:
            branches:
              only: main
